name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bahmutov/npm-install@v1
      - run: npm run build:prod
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: out
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}